### ISSUE TITLE
Optimize query suggestions for smaller screens 

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#149]
We need to improve the layout for the 11" MacBook air .

**Comment by marcosvega91** [comment]
I think that we can show a column with all suggested queries. What do you think?

**Comment by smeijer** [comment]
I'm not sure if I understand what you describe. Can you make a quick sketch in https://excalidraw.com?

**Comment by marcosvega91** [comment]
like this
![image](https://user-images.githubusercontent.com/5365582/84579003-ac10c280-adca-11ea-96f2-70e5fa47e347.png)

**Comment by smeijer** [comment]
I'm afraid that that won't help much. The problem is especially in the height of the screen. 

![20200613_231242__01](https://user-images.githubusercontent.com/1196524/84579103-81733980-adcb-11ea-8b58-90617b76a166.jpg)

**Comment by connorProgrammes** [comment]
Hi @smeijer I have an 11" MacBook and I have uploaded a gif to show the issue. It seems the scrollbar is a little too small, what if we made the overflow apart of the whole query section instead of only half the query section?

I would love to try and take a stab at it if that seems like a potential solution!

P.S I think this is such an awesome app!

![testing_library_scroll](https://user-images.githubusercontent.com/66570218/84729234-0f742f00-af48-11ea-8bee-22d4327c99fe.gif)

**Comment by smeijer** [comment]
Hi @connorProgrammes! 

Moving the scrollbars to wrap the suggestion as well, sounds like a fine solution.

I would be awesome, if you can spent some time on this, and open a pull-request. 👍

**Comment by connorProgrammes** [comment]
@smeijer Awesome! I will begin working on this later tonight and open a pull request 👍

**Comment by smeijer** [comment]
Closed by #181
