### ISSUE TITLE
add a way to switch between `query` and `events` mode

### ISSUE THREAD

**Issue by smeijer** [testing-library/testing-playground#172]
## Summary 💡

#167 added an `/event` route, yet there is no way to come there without knowing the route name. We should add a user accessible way to change mode.

## Examples 🌈

Not sure how. Add a route to the nav bar? Add mode buttons to the bottom segment?

## Motivation 🔦

Without it, users won't know that it exists.

**Comment by aganglada** [comment]
As long as I can see, the events route is the same page but with a different bottom panel. What do you think if we merge them in tabs that way users can switch between them, instead of changing routes (we can lazy load tab contents so we only load that UI if they click on the tab).

So in Playground we could have
```
|                Preview                 |
------------------------------------------
|     Queries tab.   |     Events tab    |
------------------------------------------
| Queries tab content (opened by default)|
```
What do you think @smeijer?

**Comment by smeijer** [comment]
We should definitely do that. A PR with that change would be much appreciated.

About the tabs, what do you think? Use the same link/tab style as we do in the embed dialog? Those fit nicely in between the panes.

![image](https://user-images.githubusercontent.com/1196524/98974171-e666c300-2514-11eb-8e65-70a6a53562a3.png)

**Comment by aganglada** [comment]
@smeijer Awesome! will try those and send it over!
