### ISSUE TITLE
Rename live branch to main

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/testing-playground#337]
We're moving all our repositories to use `main` as the default branch, and I'd like to rename the `develop` branch here if it doesn't impact your maintenance process too much. I wanted to submit a PR to do this, but I'm not sure how this repository gets deployed to https://testing-playground.com and https://develop.testing-playground.com, and I didn't want to break anything. If you can help me understand that, I can try to help out with the migration.

I'm also curious if we still need the `live` branch, as it seems to have almost the same code as `main`. Does it just exist to ensure that only versioned releases are deployed? If so, could we replace this with using git commit SHAs as versions, or do you want to follow semver for something like standalone installation?

**Comment by smeijer** [comment]
`develop` is the branch I'm merging pull requests to, and also the branch that's automatically deployed to `develop.testing-playground.com` using netlify's branch deploy feature.

`live` is the branch that is deployed to production. During active development, `develop` runs ahead of `live`, but once we reach stable, `live` is fast forwarded to the stable commit on `develop` and again automatically deployed.

**Comment by smeijer** [comment]
I don't hold a strong opinion regarding semver for this repo, as we don't publish any packages. But I'm not sure how we can organize the branch management differently, and still keep it simple.

I do need two branches, because we can come in the situation where I need to hotfix production, while develop is running unstable features.

**Comment by nickmccurdy** [comment]
How about we just rename `develop` to `main` then? That way the default branch name would be consistent with our other packages.

**Comment by smeijer** [comment]
Then I'd lose the connection between `develop` (branch) and `develop.testing-playground.com`. 

If something has to be renamed, `live` should be `main`. Because `main` branches are usually featured stable, while  `develop` is not (according to gitflow ¹)

But our "main" branch here, the one that contributors should base their PR on, must remain `develop` (I'm not comfortable with having every merged PR instantly being deployed to production). Having `develop` as "main branch", and `main` as the branch reflecting the live version on 'testing-playground.com', is a bit confusing.

---

1. 
<img src="https://user-images.githubusercontent.com/1196524/126122493-99190ad7-5607-4f76-898e-ebe54ecc337e.png" width=250 />

**Comment by nickmccurdy** [comment]
Ah right, I haven't used git flow in a while so I forgot it's reverted. Renaming `live` would make more sense in this case.

**Comment by smeijer** [comment]
It would. But that would be quite confusing. As the brach named  `main` then doesn't reflect our main branch.

**Comment by nickmccurdy** [comment]
Traditionally git flow used `master` as the stable branch (before the movement to rename it), and since GitHub and possibly git are moving to rename `master` to `main` anyway, I feel like using `main` as the stable branch still fits with git flow.

I don't have very strong opinions on this though, as the old branch name `master` isn't in use in this repository anyway, and there's a difference in release process from most of our repositories.
