### ISSUE TITLE
Firefox extension is gone

### ISSUE THREAD

**Issue by elevesque-nexapp** [testing-library/testing-playground#344]
## Bug Report 🐛

The firefox extension for testing playground appears to be gone: https://addons.mozilla.org/en-US/firefox/addon/testing-playground/

This is the link that the "Firefox Extension" button in the testing-playground.com menu links to.

## To Reproduce ✔️

Click the following link: https://addons.mozilla.org/en-US/firefox/addon/testing-playground/

## Expected behavior 🤔

You should navigate to the extension page page and be able to install the extension.

## Suggested solution 🔦

Don't know 🤷 

## Your Environment 💻

- _browser_: Firefox
- _os_: Mac

**Comment by smeijer** [comment]
They've revoked it because:

> Rejected by Add-ons Review Team 20 days ago
> 
> 1) Extensions defining a content security policy that allows eval ('unsafe-eval') are generally not allowed for security and performance reasons. ‘eval’ is only necessary in rare cases.
> - devtools/src/manifest.json line 24
> 
> In addition the following is required to complete the review:
> 
> 1) Please let us know to what file is '"sha256-6UcmjVDygSSU8p+3s7E7Kz8EG/ARhPADPRUm9P90HLM=" a reference for and how do you obtain it.
> - devtools/src/manifest.json line 24

I have [bad experiences with their review team](https://github.com/testing-library/testing-playground/pull/327#issuecomment-778046309), so I don't know what to do. If anyone is able and willing to submit a new version, and go through the review process, then let me know. I'm happy to add you to the authors in the Firefox Extension store. I'm personally not going to try that again.

**Comment by kevinbarabash** [comment]
Is there any way to install the extension manually using Firefox?

**Comment by davidrhoderick** [comment]
So there is no more Firefox extension then?

**Comment by kevinbarabash** [comment]
I tried installing the extension from source, but Firefox doesn't seem to recognize the folder as a valid extension and it doesn't provide any information about what might be wrong with it. 😞
