### ISSUE TITLE
Suggesting `getByText` over `getByLabelText`

### ISSUE THREAD

**Issue by zaicevas** [testing-library/testing-playground#346]
## Bug Report 🐛

Suggesting `getByText` over `getByLabelText`. As far as I understand, `getByLabelText` is of higher priority than `getByText`, according to https://testing-library.com/docs/queries/about/#priority

## To Reproduce ✔️

<img width="1743" alt="image" src="https://user-images.githubusercontent.com/34719980/172818498-2681e70c-f9cc-43d6-be20-ea540aac0f7a.png">

## Expected behavior 🤔

`getByLabelText` is suggested

## Your Environment 💻

- _browser_: Chrome
- _os_: Mac

**Comment by smeijer** [comment]
You're right. This must get fixed. Are you able to submit a pull?

**Comment by smeijer** [comment]
This comes from @testing-library/dom. I believe it's because [this function](https://github.com/testing-library/dom-testing-library/blob/d09b3c25b07486c17603317f4c5a0320c188cbed/src/label-helpers.ts#L57-L82) doesn't handle `aria-label` as a label. I'm not sure if it's a bug, or if it has a deeper accessibility reason, but the issue should be filed/fixed there.
